server.port=${PORT:0}
#server.port=8020
spring.application.name=User-MS
eureka.client.serviceUrl.defaultZone=http://localhost:8010/eureka
spring.devtools.remote.restart.enabled=true 

#load balancer

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id}:${random.value}